unit uMIConstants;

interface

const
	mi_M_TOOLS_SELECTOR = 1701;
	mi_M_TOOLS_SEARCH_RECT = 1722;
	mi_M_TOOLS_SEARCH_RADIUS = 1703;
	mi_M_TOOLS_SEARCH_BOUNDARY = 1704;
	mi_M_TOOLS_EXPAND = 1705;
	mi_M_TOOLS_ZOOM_IN = mi_M_TOOLS_EXPAND;
	mi_M_TOOLS_SHRINK = 1706;
	mi_M_TOOLS_ZOOM_OUT = mi_M_TOOLS_SHRINK;
	mi_M_TOOLS_RECENTER = 1702;
	mi_M_TOOLS_PAN = mi_M_TOOLS_RECENTER;
	mi_M_TOOLS_PNT_QUERY = 1707;
	mi_M_TOOLS_INFO = mi_M_TOOLS_PNT_QUERY;
	mi_M_TOOLS_LABELER = 1708;
	mi_M_TOOLS_RULER = 1710;
	mi_M_TOOLS_DRAGWINDOW = 1734;
	mi_M_TOOLS_SYMBOL = 1711;
	mi_M_TOOLS_LINE = 1712;
	mi_M_TOOLS_POLYLINE = 1713;
	mi_M_TOOLS_ARC = 1716;
	mi_M_TOOLS_POLYGON = 1714;
	mi_M_TOOLS_ELLIPSE = 1715;
	mi_M_TOOLS_RECTANGLE = 1717;
	mi_M_TOOLS_ROUNDEDRECT = 1718;
	mi_M_TOOLS_TEXT = 1709;
  mi_M_TOOLS_FRAME = 1719;

implementation

end.
