C      FILE: DISCOF.INC
C================================================================
C      THIS FILE DEFINES THE VARIABLES COMMON TO THE FREE
C      AND SUBMERGED ALGORITHM ROUTINES
C================================================================
       REAL GOF, GOS, GOPH, RADPH, Y2PH, Y3PH
       COMMON /DISCOF/ GOF, GOS, GOPH, RADPH, Y2PH, Y3PH
C================================================================

