C      FILE: RGFLOW.INC
C================================================================
C     THIS FILE DEFINES THE COMMON VARIABLES USED IN THE FREE
C     AND SUBMERGED COMPUTATIONS
C================================================================
      DIMENSION QGATE(NRADG),CDRG(NRADG),CFLRVS(NRADG)
      COMMON /RGFLOW/ QG,QFREE,QSUB,QGATE,QF,QS,FCOND,CFLRVS,CDRG
C================================================================
