C      FILE: FLCOMN.INC
C================================================================
C     THIS FILE DEFINES THE VARIABLES COMMON TO THE DISCHARGE
C     COMPUTATIONS AND TO THE ROUTINE WHICH DETERMINES
C     THE FLOW CONDITION
C================================================================
      REAL DY, DC, Y2, Y3, EGC, EG2, EG3
      COMMON /FLCOMN/ DY, DC, Y2, Y3, EGC, EG2, EG3
C================================================================
