C      FILE:RGPRNT.INC
C=================================================================
C    THIS FILE DEFINES THE VARIABLES USED TO STORE THE DISCHARGE
C     HISTORY FOR RADIAL GATES
C=================================================================
       DIMENSION PRTRGQ(NRADG), PRTGPN(NRADG)
       COMMON /RGPRNT/ PRTRGQ, PRTGPN
C=================================================================
