      FUNCTION LDATE(JDAY)

C
C THIS FUNC COMPUTES SERIAL DATE SINCE 1/1/1900 TO THE STARTING DATE
C  AND THEN COMPUTES THE SWMM4 STANDARD DAY OF WEEK INDEX No. ALA
C  THE TECHNIQUE IN LOTUS 123.
C
      LDATE=0
      IYR=JDAY/1000
      JEWEL=JDAY-IYR*1000
      DO 5 I=1,IYR
       LDATE=LDATE+365
       IF(MOD(I-1,4).EQ.0)LDATE=LDATE+1
5     CONTINUE
      LDATE=LDATE+JEWEL
      LDATE=MOD(LDATE,7)
      IF(LDATE.LT.1)LDATE=7
C
      RETURN
      END
